### ISSUE TITLE
Interaction with slf4j-timbre?

### ISSUE THREAD

**Issue by WhittlesJr** [duct-framework/logger.timbre#6]
Hi, I'm trying to consume logs from a Java library that emits via SLF4J. [slf4j-timbre](https://github.com/fzakaria/slf4j-timbre) is supposed to do this, but I'm not seeing any logs come through. 

Am I missing something in my config? slf4j-timbre is seemingly supposed to be config-less. 

My config:

```
(def system-config
  {:duct.profile/dev {:duct.logger.timbre/brief {:min-level :trace}})
   :duct.module/logging {}})
```

deps.edn includes:
```
:deps {com.fzakaria/slf4j-timbre  {:mvn/version "0.3.19"}
       org.slf4j/log4j-over-slf4j {:mvn/version "1.7.30"}}
```

**Comment by WhittlesJr** [comment]
The Java library is https://github.com/infiniteautomation/BACnet4J. It's totally possible that something completely unrelated to logging is screwed up.

**Comment by weavejester** [comment]
You could try running `lein deps :tree` and see if there are any dependencies that include a slf4j no-op logger.

**Comment by WhittlesJr** [comment]
As for slf4j-related libs, all I'm seeing is: 
```
org.slf4j/log4j-over-slf4j 1.7.30
org.slf4j/slf4j-api 1.7.30
com.fzakaria/slf4j-timbre 0.3.19
```

**Comment by weavejester** [comment]
Have you tried setting `:set-root-config?` to `true`?

**Comment by WhittlesJr** [comment]
Ah, that was it! Thank you!
