### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hden** [duct-framework/logger.timbre#7]
The dependencies included in this library is quite old, for example latest timbre is `[com.taoensso/timbre "5.1.2"]`.
I guess you have a lot to maintain. How can I help? Maybe we can setup tools such as [Renovate](https://github.com/renovatebot/renovate)?

**Comment by weavejester** [comment]
Dependencies updated and 0.5.0 released. I had to update the tests as well, so Renovate probably wouldn't have helped in this instance I'm afraid.
